---

version: "3.7"

services:
  es:
    container_name: tla-prototype-es
    image: elasticsearch:7.7.1
    ports:
      - ${ES_PORT}:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    stdin_open: true
    tty: true

  populate:
    container_name: tla-prototype-ingest
    build:
      context: .
    depends_on:
      - es
    environment:
      ES_URL: http://es:9200
      SAMPLE_URL: ${SAMPLE_URL}
    command: "ingest"

  app:
    container_name: tla-prototype
    build:
      context: .
    depends_on:
      - populate
    ports:
      - ${LISTEN_PORT}:8000
    environment:
      ES_URL: http://es:9200
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:?err}

...
