version: "3.7"

services:
  es:
    image: elasticsearch:6.5.4
    ports:
      - ${ES_PORT}:9200
    environment:
      discovery.type: single-node
    stdin_open: true
    tty: true


  tla:
    build:
      context: .
    depends_on:
      - es
    ports:
      - ${LISTEN_PORT}:8000
 
