version: "3.7"

services:
  es:
    image: elasticsearch:6.5.4
    ports:
      - ${ES_PORT}:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    stdin_open: true
    tty: true

  tla:
    build:
      context: .
      args:
        sample_url: ${SAMPLE_URL}
    depends_on:
      - es
    ports:
      - ${LISTEN_PORT}:8000
    environment:
      ES_URL: http://es:9200
    volumes:
      - type: bind
        source: "./webd"
        target: /app/webd
        volume:
          nocopy: true
          consistency: consistent
